import { useQuery } from "@tanstack/react-query";
import { BookOpen, FileText, Layers3, Search, SlidersHorizontal } from "lucide-react";
import { api } from "../api/client";
import { Panel } from "../components/Panel";

type DocumentItem = { id: string; name: string; category: string; topic: string; year: number; region: string };
const categoryColors: Record<string, string> = { energy: "energy", emissions: "emissions", climate: "climate", water: "water" };

export function KnowledgePage() {
  const documents = useQuery({ queryKey: ["documents"], queryFn: () => api<{ documents: DocumentItem[] }>("/api/v1/documents") });
  const grouped = documents.data?.documents.reduce<Record<string, DocumentItem[]>>((groups, item) => { (groups[item.category] ??= []).push(item); return groups; }, {}) ?? {};
  return <main className="page-shell"><header className="topbar"><div className="brand"><span className="brand-mark"><BookOpen size={17} /></span><span>Knowledge <strong>Base</strong></span></div><div className="topbar-meta"><span className="live-dot" /> INDEXED CORPUS / {documents.data?.documents.length ?? 0} DOCUMENTS</div></header><section className="page-heading knowledge-heading"><span className="eyebrow"><BookOpen size={14} /> GREEN TECH KNOWLEDGE GRAPH</span><h1>A living library<br /><em>for better decisions.</em></h1><p>Browse the evidence layer behind every research answer. Documents are chunked, embedded, and filtered by category, topic, year, and region.</p><div className="knowledge-toolbar"><div><Search size={16} /><span>Search indexed knowledge</span></div><button type="button"><SlidersHorizontal size={15} /> Filters</button></div></section><section className="knowledge-overview"><div><strong>{documents.data?.documents.length ?? 0}</strong><span>indexed documents</span></div><div><strong>{Object.keys(grouped).length}</strong><span>knowledge domains</span></div><div><strong>20</strong><span>retrieval candidates</span></div><div><strong>8</strong><span>evidence chunks / answer</span></div></section><div className="knowledge-groups">{Object.entries(grouped).map(([category, items]) => <section className={`knowledge-group ${categoryColors[category] ?? ""}`} key={category}><div className="knowledge-group-title"><div><span className="domain-mark"><Layers3 size={16} /></span><h2>{category}</h2></div><span>{items.length} documents</span></div><div className="document-grid">{items.sort((a, b) => b.year - a.year).map((item) => <article className="document-card" key={item.id}><div className="document-card-top"><FileText size={17} /><span>{item.year}</span></div><h3>{item.name.replace(".md", "")}</h3><p>{item.topic.replaceAll("-", " ")}</p><footer><span>{item.region}</span><span>READY FOR RAG</span></footer></article>)}</div></section>)}</div><Panel title="How indexing works" icon={<Layers3 size={17} />}><div className="indexing-flow"><span>Markdown / text</span><b>→</b><span>Chunk + metadata</span><b>→</b><span>Embedding cache</span><b>→</b><span>pgvector index</span></div></Panel></main>;
}
